apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argo-cd
spec:
  secretName: argocd-tls
  dnsNames:
    - argocd.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
