global:
  domain: argocd.flapi.org

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt-production
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    tls: true
    extraTls:
      - hosts:
          - argocd.flapi.org
        secretName: argocd-tls